//-----------------------------------------------------------------------// <copyright file="AttributeRegistry.cs" company="Sirenix IVS"> // Copyright (c) Sirenix IVS. All rights reserved.// </copyright>//-----------------------------------------------------------------------
//-----------------------------------------------------------------------
// <copyright file="AttributeRegistry.cs" company="Sirenix IVS">
// Copyright (c) Sirenix IVS. All rights reserved.
// </copyright>
//-----------------------------------------------------------------------

using Sirenix.OdinInspector;

[assembly: RegisterAttribute(typeof(AssetListAttribute), "Type Specifics")]
[assembly: RegisterAttribute(typeof(AssetsOnlyAttribute), "Essentials")]
[assembly: RegisterAttribute(typeof(BoxGroupAttribute), "Groups")]
[assembly: RegisterAttribute(typeof(ButtonAttribute), "Groups", "Buttons")]
[assembly: RegisterAttribute(typeof(ButtonGroupAttribute), "Groups", "Buttons")]
[assembly: RegisterAttribute(typeof(ColorPaletteAttribute), "Type Specifics")]
[assembly: RegisterAttribute(typeof(CustomContextMenuAttribute), "Misc")]
[assembly: RegisterAttribute(typeof(CustomValueDrawerAttribute), "Essentials")]
[assembly: RegisterAttribute(typeof(DelayedPropertyAttribute), "Essentials")]
[assembly: RegisterAttribute(typeof(DetailedInfoBoxAttribute), "Essentials")]
[assembly: RegisterAttribute(typeof(DictionaryDrawerSettings), "Collections")]
[assembly: RegisterAttribute(typeof(DisableContextMenuAttribute), "Misc")]
[assembly: RegisterAttribute(typeof(DisableIfAttribute), "Essentials")]
[assembly: RegisterAttribute(typeof(DisableInEditorModeAttribute), "Essentials")]
[assembly: RegisterAttribute(typeof(DisableInInlineEditorsAttribute), "Essentials")]
[assembly: RegisterAttribute(typeof(DisableInNonPrefabsAttribute), "Essentials")]
[assembly: RegisterAttribute(typeof(DisableInPlayModeAttribute), "Essentials")]
[assembly: RegisterAttribute(typeof(DisableInPrefabAssetsAttribute), "Essentials")]
[assembly: RegisterAttribute(typeof(DisableInPrefabInstancesAttribute), "Essentials")]
[assembly: RegisterAttribute(typeof(DisableInPrefabsAttribute), "Essentials")]
[assembly: RegisterAttribute(typeof(DisplayAsStringAttribute), "Type Specifics")]
[assembly: RegisterAttribute(typeof(DontApplyToListElementsAttribute), "Misc")]
[assembly: RegisterAttribute(typeof(DrawWithUnityAttribute), "Misc")]
[assembly: RegisterAttribute(typeof(EnableGUIAttribute), "Essentials")]
[assembly: RegisterAttribute(typeof(EnableIfAttribute), "Essentials")]
[assembly: RegisterAttribute(typeof(EnumPagingAttribute), "Type Specifics", "Buttons")]
[assembly: RegisterAttribute(typeof(EnumToggleButtonsAttribute), "Type Specifics", "Buttons")]
[assembly: RegisterAttribute(typeof(FilePathAttribute), "Type Specifics")]
[assembly: RegisterAttribute(typeof(FolderPathAttribute), "Type Specifics")]
[assembly: RegisterAttribute(typeof(FoldoutGroupAttribute), "Groups")]
[assembly: RegisterAttribute(typeof(GUIColorAttribute), "Essentials")]
[assembly: RegisterAttribute(typeof(HideIfAttribute), "Essentials")]
[assembly: RegisterAttribute(typeof(PreviewFieldAttribute), "Type Specifics")]
[assembly: RegisterAttribute(typeof(OnValueChangedAttribute), "Misc")]
[assembly: RegisterAttribute(typeof(OnInspectorGUIAttribute), "Misc")]
[assembly: RegisterAttribute(typeof(MultiLinePropertyAttribute), "Type Specifics")]
[assembly: RegisterAttribute(typeof(MinValueAttribute), "Type Specifics")]
[assembly: RegisterAttribute(typeof(MinMaxSliderAttribute), "Type Specifics")]
[assembly: RegisterAttribute(typeof(MaxValueAttribute), "Type Specifics")]
[assembly: RegisterAttribute(typeof(ListDrawerSettingsAttribute), "Collections")]
[assembly: RegisterAttribute(typeof(LabelWidthAttribute), "Misc")]
[assembly: RegisterAttribute(typeof(LabelTextAttribute), "Misc")]
[assembly: RegisterAttribute(typeof(InlinePropertyAttribute), "Misc")]
[assembly: RegisterAttribute(typeof(InlineEditorAttribute), "Type Specifics")]
[assembly: RegisterAttribute(typeof(InlineButtonAttribute), "Buttons")]
[assembly: RegisterAttribute(typeof(InfoBoxAttribute), "Misc")]
[assembly: RegisterAttribute(typeof(IndentAttribute), "Misc")]
[assembly: RegisterAttribute(typeof(HorizontalGroupAttribute), "Groups")]
[assembly: RegisterAttribute(typeof(HideReferenceObjectPickerAttribute), "Type Specifics")]
[assembly: RegisterAttribute(typeof(HideNetworkBehaviourFieldsAttribute), "Type Specifics")]
[assembly: RegisterAttribute(typeof(HideMonoScriptAttribute), "Type Specifics")]
[assembly: RegisterAttribute(typeof(HideLabelAttribute), "Essentials")]
[assembly: RegisterAttribute(typeof(HideInTablesAttribute), "Type Specifics")]
[assembly: RegisterAttribute(typeof(HideInPrefabsAttribute), "Essentials")]
[assembly: RegisterAttribute(typeof(HideInPrefabInstancesAttribute), "Essentials")]
[assembly: RegisterAttribute(typeof(HideInPrefabAssetsAttribute), "Essentials")]
[assembly: RegisterAttribute(typeof(HideInPlayModeAttribute), "Essentials")]
[assembly: RegisterAttribute(typeof(HideInNonPrefabsAttribute), "Essentials")]
[assembly: RegisterAttribute(typeof(HideInInlineEditorsAttribute), "Type Specifics")]
[assembly: RegisterAttribute(typeof(HideInEditorModeAttribute), "Essentials")]
[assembly: RegisterAttribute(typeof(ProgressBarAttribute), "Type Specifics")]
[assembly: RegisterAttribute(typeof(WrapAttribute), "Type Specifics")]
[assembly: RegisterAttribute(typeof(VerticalGroupAttribute), "Groups")]
[assembly: RegisterAttribute(typeof(ValueDropdownAttribute), "Essentials", "Collections")]
[assembly: RegisterAttribute(typeof(ValidateInputAttribute), "Essentials")]
[assembly: RegisterAttribute(typeof(TypeInfoBoxAttribute), "Essentials")]
[assembly: RegisterAttribute(typeof(TypeFilterAttribute), "Essentials")]
[assembly: RegisterAttribute(typeof(ToggleLeftAttribute), "Type Specifics")]
[assembly: RegisterAttribute(typeof(ToggleGroupAttribute), "Groups")]
[assembly: RegisterAttribute(typeof(ToggleAttribute), "Type Specifics")]
[assembly: RegisterAttribute(typeof(TitleGroupAttribute), "Groups")]
[assembly: RegisterAttribute(typeof(TitleAttribute), "Essentials")]
[assembly: RegisterAttribute(typeof(TableMatrixAttribute), "Type Specifics", "Collections")]
[assembly: RegisterAttribute(typeof(TableListAttribute), "Type Specifics", "Collections")]
[assembly: RegisterAttribute(typeof(TableColumnWidthAttribute), "Collections")]
[assembly: RegisterAttribute(typeof(TabGroupAttribute), "Groups")]
[assembly: RegisterAttribute(typeof(SuppressInvalidAttributeErrorAttribute), "Meta")]
[assembly: RegisterAttribute(typeof(SuffixLabelAttribute), "Misc")]
[assembly: RegisterAttribute(typeof(ShowPropertyResolverAttribute), "Debug")]
[assembly: RegisterAttribute(typeof(ShowInInspectorAttribute), "Essentials")]
[assembly: RegisterAttribute(typeof(ShowInInlineEditorsAttribute))]
[assembly: RegisterAttribute(typeof(ShowIfAttribute), "Essentials")]
[assembly: RegisterAttribute(typeof(ShowDrawerChainAttribute), "Debug")]
[assembly: RegisterAttribute(typeof(SceneObjectsOnlyAttribute), "Type Specifics")]
[assembly: RegisterAttribute(typeof(ResponsiveButtonGroupAttribute), "Groups", "Buttons")]
[assembly: RegisterAttribute(typeof(RequiredAttribute), "Essentials")]
[assembly: RegisterAttribute(typeof(ReadOnlyAttribute), "Essentials")]
[assembly: RegisterAttribute(typeof(PropertyTooltipAttribute), "Misc")]
[assembly: RegisterAttribute(typeof(PropertySpaceAttribute), "Essentials")]
[assembly: RegisterAttribute(typeof(PropertyRangeAttribute), "Type Specifics")]
[assembly: RegisterAttribute(typeof(PropertyOrderAttribute), "Essentials")]